version: '3'

services:
    sciencebeam-gym-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                install_dev: y
        image: elifesciences/sciencebeam-gym-dev:${IMAGE_TAG}
