version: '3'

services:
    sciencebeam-gym:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                install_dev: y
        image: elifesciences/sciencebeam-gym:${IMAGE_TAG}
