version: '3.4'

services:
  sciencebeam-gym:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args: 
        install_dev: n
    image: elifesciences/sciencebeam-gym:${IMAGE_TAG}
    command: /bin/sh -c exit 0

  sciencebeam-gym-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args: 
        install_dev: y
    image: elifesciences/sciencebeam-gym_dev:${IMAGE_TAG}
